name: bsky-bot
on:
  schedule:
    # Run every 3 hours.
    - cron: '0 */3 * * *'
  workflow_dispatch: # This allows manually running the workflow from the GitHub actions page
concurrency:
  group: bsky-bot
jobs:
  rss-to-bluesky:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
      - name: Generate cache key
        uses: actions/github-script@v7
        id: generate-key
        with:
          script: |
            core.setOutput('cache-key', new Date().valueOf())
      - name: Retrieve cache
        uses: actions/cache@v4
        with:
          path: ${{ github.workspace }}/bsky-bot
          key: feed-cache-${{ steps.generate-key.outputs.cache-key }}
          restore-keys: feed-cache-
      - name: Install dependencies
        run: npm ci
      - name: Post to Bluesky
        run: npm start -- --rss-feed='https://echojs.com/rss' --cache-file='${{ github.workspace }}/bsky-bot/cache.json'
        env:
          BSKY_SERVICE: https://bsky.social
          BSKY_HANDLE: ${{ vars.BSKY_HANDLE }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
